#!/bin/bash
echo "🚀 Setting up GitHub repository..."
echo ""
echo "📋 Instructions:"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: personal-website"
echo "3. Description: Enterprise-level portfolio with React, TypeScript, and Framer Motion"
echo "4. Keep it Public (or Private if you prefer)"
echo "5. DO NOT initialize with README, .gitignore, or license"
echo "6. Click 'Create repository'"
echo ""
echo "After creating the repository, run these commands:"
echo ""
echo "git remote add origin https://github.com/1000luca/personal-website.git"
echo "git push -u origin main"
echo ""
